### ISSUE TITLE
Mobs in old shops dropping tons of loot

### ISSUE THREAD

**Issue by OldGrama** [OldGrama/VanillaHub#13]
**Describe the bug**
mobs killed in the old shop area drop a ton of loot when killed such as 30 string from 1 spider

**To Reproduce**
1. go to /warp oldshops
2. kill mobs roaming in shops

**Expected behavior**
normal drop rates

**Screenshots**
https://imgur.com/a/3amQIJR

**Comment by OldGrama** [comment]
added a temporary fix, disabled animal damage within the region

**Comment by sxphirus** [comment]
i believe this is due to a "testing" feature in shopkeepers, all shopkeepers have crazy high drop rates so you can easily tell which one is which when bug testing.

this issue will be fixed as soon as we either : update the plugin sunday or wednesday
remove old shops to stop mob duplication (mobs are duping because chunks are being "lazy" and not running the correct cycles.
